// Storage keys are always "<folder>/<uuid>.<ext>", generated by us. Anything
// else is refused before it reaches the disk or S3, so a key can never be
// used for path traversal ("../") or to read another folder.

export type Bucket = "public" | "private";

export type ImageExtension = "jpg" | "png" | "webp";

export const CONTENT_TYPES: Record<ImageExtension, string> = {
  jpg: "image/jpeg",
  png: "image/png",
  webp: "image/webp",
};

const KEY_PATTERN = /^(products|logos|receipts)\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}\.(jpg|png|webp)$/;

export function isValidKey(key: string): boolean {
  return KEY_PATTERN.test(key);
}

export function assertValidKey(key: string): void {
  if (!isValidKey(key)) throw new Error(`Invalid storage key: ${JSON.stringify(key)}`);
}

export function contentTypeOf(key: string): string {
  const ext = key.slice(key.lastIndexOf(".") + 1) as ImageExtension;
  return CONTENT_TYPES[ext];
}
